from typing import Annotated, TypedDict, List, Dict, Optional, Union
from pydantic import BaseModel, Field
from langgraph.graph.message import add_messages

# ==========================================
# 1. ACTION SCHEMA (The "Symbolic" Output)
# ==========================================
class AgentAction(BaseModel):
    """
    Structured output from Gemini to dictate deterministic steps.
    This ensures the LLM plans the trip, but the code drives the car.
    """
    action_type: str = Field(description="The type of action: 'NAVIGATE', 'CLICK', 'INPUT', 'WAIT', 'SCRAPE', 'SOLVE_CAPCHA'")
    selector: Optional[str] = Field(None, description="The CSS or Playwright selector for the target element")
    value: Optional[str] = Field(None, description="The text to type or the URL to navigate to")
    thought: str = Field(description="The internal reasoning behind this specific action")

# ==========================================
# 2. STATE SCHEMA (The "Graph" Memory)
# ==========================================
class AgentState(TypedDict):
    """
    The central state object for the Arvyn LangGraph workflow.
    This structure is serialized and persisted during 'Conscious Pauses'.
    """
    # 'messages' tracks the conversation history between User and AI
    # Annotated with add_messages so new messages are appended, not overwritten
    messages: Annotated[List[Dict[str, str]], add_messages]
    
    # 'user_data' stores information retrieved from user_profile.json
    user_data: Dict[str, str]
    
    # 'missing_fields' tracks what the agent still needs to ask the user
    missing_fields: List[str]
    
    # 'execution_plan' holds the sequence of AgentActions generated by Gemini
    execution_plan: List[AgentAction]
    
    # 'current_screenshot' stores base64 encoded images for Explorer Mode
    current_screenshot: Optional[str]
    
    # 'status' tracks the state machine's current node (e.g., 'navigating', 'approving')
    status: str
    
    # 'last_error' for self-healing and error-recovery cycles
    last_error: Optional[str]
    
    # 'is_approved' serves as the gate for Human-in-the-Loop (HITL) logic
    is_approved: bool

# ==========================================
# 3. DOM SCHEMA (For Structured UI Understanding)
# ==========================================
class UIElement(BaseModel):
    """Represents a simplified version of a DOM element for Gemini's analysis."""
    tag: str
    attributes: Dict[str, str]
    text: Optional[str]
    bounding_box: Optional[Dict[str, float]] # Used for Explorer Mode grounding