import os
import sys
import socket
import asyncio
import platform
from dotenv import load_dotenv

# Try importing the required library based on the Blueprint
try:
    from google import genai
    from google.genai import types
except ImportError:
    print("\n\033[91m[CRITICAL] The 'google-genai' library is missing.\033[0m")
    print("Please install it using: pip install google-genai")
    sys.exit(1)

# ANSI Color Codes for readable output
GREEN = "\033[92m"
RED = "\033[91m"
YELLOW = "\033[93m"
CYAN = "\033[96m"
RESET = "\033[0m"

def print_status(step, status, message=""):
    if status == "PASS":
        print(f"[{step}] {GREEN}PASS{RESET} {message}")
    elif status == "FAIL":
        print(f"[{step}] {RED}FAIL{RESET} {message}")
    elif status == "WARN":
        print(f"[{step}] {YELLOW}WARN{RESET} {message}")
    else:
        print(f"[{step}] {CYAN}INFO{RESET} {message}")

def check_cdp_port(host="127.0.0.1", port=9222):
    """
    Checks if the Chrome Debugging Port is open and listening.
    """
    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.settimeout(2)  # 2 second timeout
        result = sock.connect_ex((host, int(port)))
        sock.close()
        return result == 0
    except Exception as e:
        return False

def generate_launch_script():
    """Generates a robust launch script to force Chrome into debug mode."""
    os_name = platform.system()
    script_name = ""
    content = ""

    if os_name == "Windows":
        script_name = "launch_arvyn_chrome.bat"
        # Uses a temp profile to ensure it doesn't conflict with existing Chrome instances
        content = r"""@echo off
echo Starting ISOLATED Chrome instance for Arvyn...
echo This ensures Port 9222 is available even if other Chromes are open.
start "" "chrome.exe" --remote-debugging-port=9222 --user-data-dir="%TEMP%\arvyn-debug-profile" --no-first-run --no-default-browser-check
echo Chrome launched. Please verify a new window appeared.
pause
"""
    elif os_name == "Darwin": # macOS
        script_name = "launch_arvyn_chrome.sh"
        content = r"""#!/bin/bash
echo "Starting ISOLATED Chrome instance..."
"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" --remote-debugging-port=9222 --user-data-dir="/tmp/arvyn-debug-profile" --no-first-run &
echo "Chrome launched."
"""
    else: # Linux
        script_name = "launch_arvyn_chrome.sh"
        content = r"""#!/bin/bash
echo "Starting ISOLATED Chrome instance..."
google-chrome --remote-debugging-port=9222 --user-data-dir="/tmp/arvyn-debug-profile" --no-first-run &
"""

    if script_name:
        try:
            with open(script_name, "w") as f:
                f.write(content)
            if os_name != "Windows":
                os.chmod(script_name, 0o755)
            return script_name
        except Exception as e:
            return None
    return None

def print_chrome_help():
    print(f"\n{YELLOW}=== How to Fix Chrome Connection ==={RESET}")
    print(f"{RED}Issue Detected:{RESET} Chrome is ignoring the port request because of background processes.")
    
    print(f"\n{CYAN}SOLUTION: Use the generated launch script.{RESET}")
    script_name = generate_launch_script()
    if script_name:
        print(f"1. I have generated a script named: {GREEN}{script_name}{RESET}")
        print(f"2. Run this script file from your file explorer or terminal.")
        print(f"   (It creates a temporary profile so it won't conflict with your main browser)")
        print("3. Wait for the NEW blank Chrome window to open.")
        print("4. Re-run this diagnostic tool.")
    else:
        print("Could not generate script. Please try this command which uses a unique profile:")
        print(r'chrome.exe --remote-debugging-port=9222 --user-data-dir="%TEMP%\arvyn-unique"')

def create_env_template():
    """Creates a template .env file if it doesn't exist."""
    template = """# Arvyn Environment Configuration
# Generated by diagnostic_tool.py

# API Keys (Google AI Studio)
GEMINI_API_KEY=your_google_api_key_here
STT_API_KEY=your_google_api_key_here

# Playwright Configuration
CDP_DEBUG_PORT=9222

# IPC Configuration
SOCKETIO_SERVER_URL=http://localhost:8000
"""
    try:
        with open(".env", "w") as f:
            f.write(template)
        print_status("Setup", "PASS", "Created template .env file.")
        print(f"{YELLOW}Action Required: Open .env and paste your actual API keys.{RESET}")
    except Exception as e:
        print_status("Setup", "FAIL", f"Could not create .env file: {e}")

async def test_key(key_name, api_key):
    """
    Tests a specific API key by making a lightweight call to the Gemini 2.5 Flash model.
    """
    if not api_key:
        print_status(key_name, "FAIL", "Key is empty or None.")
        return False

    if api_key.startswith("your_") or "key_here" in api_key:
        print_status(key_name, "FAIL", "Key appears to be a placeholder from the template.")
        return False

    try:
        client = genai.Client(api_key=api_key)
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents="Reply with 'OK'."
        )
        
        if response.text:
            print_status(key_name, "PASS", "Authentication successful. Model replied.")
            return True
        else:
            print_status(key_name, "WARN", "Authentication seemed okay, but response was empty.")
            return True

    except Exception as e:
        error_msg = str(e)
        if "400" in error_msg or "INVALID_ARGUMENT" in error_msg:
             print_status(key_name, "FAIL", "Key rejected. Check if you copied the full string.")
        elif "401" in error_msg or "UNAUTHENTICATED" in error_msg:
             print_status(key_name, "FAIL", "Key rejected (Unauthenticated). The key is invalid or expired.")
        elif "403" in error_msg:
             print_status(key_name, "FAIL", "Permission denied. Ensure the key has access to Generative Language API.")
        else:
             print_status(key_name, "FAIL", f"Unexpected error: {error_msg}")
        return False

async def main():
    print(f"{CYAN}=== Arvyn System Diagnostic Tool v3 (Windows Fix) ==={RESET}\n")

    # 1. Check .env file existence
    env_path = os.path.join(os.getcwd(), ".env")
    if os.path.exists(env_path):
        print_status("Environment", "PASS", f"Found .env at {env_path}")
        load_dotenv(env_path)
    else:
        print_status("Environment", "WARN", "No .env file found.")
        create_env = input(f"{YELLOW}Do you want to generate a template .env file? (y/n): {RESET}")
        if create_env.lower().startswith('y'):
            create_env_template()
            return 
        else:
            print_status("Environment", "FAIL", "Cannot proceed without configuration.")
            return

    # 2. Check Key Presence
    stt_key = os.getenv("STT_API_KEY")
    gemini_key = os.getenv("GEMINI_API_KEY")
    cdp_port = os.getenv("CDP_DEBUG_PORT", "9222") 
    socket_url = os.getenv("SOCKETIO_SERVER_URL")

    if stt_key: print_status("STT_API_KEY", "PASS", "Variable found.")
    else: print_status("STT_API_KEY", "FAIL", "Variable missing.")

    if gemini_key: print_status("GEMINI_API_KEY", "PASS", "Variable found.")
    else: print_status("GEMINI_API_KEY", "FAIL", "Variable missing.")

    # 3. CRITICAL: Test Chrome Connection
    print(f"\n{CYAN}--- Testing Chrome Connection (CDP) ---{RESET}")
    cdp_ready = check_cdp_port("127.0.0.1", cdp_port)
    
    if cdp_ready:
        print_status("Chrome CDP", "PASS", f"Connected to Chrome on port {cdp_port}.")
    else:
        print_status("Chrome CDP", "FAIL", f"Could not connect to Chrome on port {cdp_port}.")
        print_chrome_help()

    # 4. Validation Phase
    print(f"{CYAN}--- Testing API Connectivity ---{RESET}")
    all_passed = True
    
    if stt_key:
        if not await test_key("STT Key Test", stt_key): all_passed = False
    
    if gemini_key and gemini_key != stt_key:
        if not await test_key("Cognitive Key Test", gemini_key): all_passed = False

    # 5. Summary
    print(f"\n{CYAN}=== Diagnostic Summary ==={RESET}")
    if all_passed and stt_key and gemini_key and cdp_ready:
        print(f"{GREEN}SUCCESS: System is ready.{RESET}")
        print(f"Run the server with: {CYAN}uvicorn main:app --reload{RESET}")
    else:
        print(f"{RED}FAILURE: Please resolve the issues above.{RESET}")
        if not cdp_ready:
            print(f"{YELLOW}RUN THE 'launch_arvyn_chrome.bat' SCRIPT GENERATED ABOVE!{RESET}")

if __name__ == "__main__":
    asyncio.run(main())